### ISSUE TITLE
Næste/forrige spørgsmål

### ISSUE THREAD

**Issue by Victorschimmell** [Victorschimmell/MiniEksamensprojekt#5]
To knapper skal laves, så man kan gå frem og tilbage mellem spørgsmålene.

**Comment by EdwardR7** [comment]
Knapperne og deres funktionalitet mellem siderne er der, så det handler egentlig om at få lavet "spørgsmål præsentation", så vi kan gøre det hele variabelt. Firkantet set er iterationen done, men jeg lader den være et åbent issue, da den afhænger af det andet, som arbejdes på (ik helt færdig).
